Woche8
Koch-Dustin/Cs50Kurs pull request #10
Opened 2022-09-22 06:22 UTC by Koch-Dustin

Changes:
   - Add trivia
   - Add homepage

PR: #10

2022-09-22 08:35 UTC, stefanluth reviewed
Why is week 0 - 3 included and deleted?

2022-09-23 08:05 UTC, Koch-Dustin commented
> 

I don't know why it was there i just deleted it because i don't need it in this Branch

2022-09-23 18:48 UTC, stefanluth commented
Merging this branch will delete the files on develop. Undo the deletion.

2022-09-26 07:12 UTC, Koch-Dustin commented
> Merging this branch will delete the files on develop. Undo the deletion.

I don't know how to Undo it, could you help me when you have time for it?

2022-09-26 07:25 UTC, stefanluth commented
Try reverting the commit which deleted the files:

```zsh
git revert d893744
git add .
git commit .
git push
```

2022-09-29 12:07 UTC, stefanluth requested changes
1. Add EOFs
2. Use 2 spaces for indentation in HTML, JS, CSS files
3. Add proper spacings after if, else, etc.

2022-09-29 12:07 UTC, stefanluth commented on homepage/Kontakt/kontakt.html
> +</html>
EOF

2022-09-29 12:07 UTC, stefanluth commented on homepage/Portfolio/index.js
> +    if(menu1_is_open) {
```suggestion
    if (menu1_is_open) {
```
Everywhere

2022-09-29 13:15 UTC, FrederikFricke requested changes

2022-09-29 13:15 UTC, FrederikFricke commented on homepage/Kontakt/kontakt.html
> +</html>
End of file

2022-09-29 13:15 UTC, FrederikFricke commented on homepage/Portfolio/portfolio.html
> +</html>
end of file

2022-09-29 13:15 UTC, FrederikFricke commented on homepage/Portfolio/style.css
> +}
end of file

2022-09-29 13:15 UTC, FrederikFricke commented on homepage/Socialmedia/Socialmedia.html
> +</html>
end of file

2022-09-29 13:15 UTC, FrederikFricke commented on homepage/Socialmedia/style.css
> +}
end of file

2022-09-29 13:15 UTC, FrederikFricke commented on trivia/index.html
> +                    change_content_part_one("Incorrect");
```suggestion
                if (IncorrectPartOne == false) {
                    change_content_part_one("Correct");
                    AnswerAlert.style.color = "green";
                } else {
                    change_content_part_one("Incorrect");
```

Check other places as well

2022-09-29 13:15 UTC, FrederikFricke commented on trivia/index.html
> +
Todo? still needed?

2022-09-29 13:17 UTC, Nicojele requested changes

2022-09-29 13:17 UTC, Nicojele commented on homepage/Portfolio/index.js
> +    }else {
add space

2022-09-29 13:17 UTC, Nicojele commented on homepage/Portfolio/index.js
> +    }else {
same

2022-09-29 13:17 UTC, Nicojele commented on homepage/Portfolio/index.js
> +    }else {
same

2022-09-29 13:17 UTC, Nicojele commented on trivia/styles.css
> +.section h4{
same

2022-09-29 13:39 UTC, FrederikFricke requested changes

2022-09-29 13:39 UTC, FrederikFricke commented on trivia/index.html
> +        <h4 id="IncorrectAnswerTwo">Incorrect</h4>
Todo still needed?

2022-09-29 13:43 UTC, FrederikFricke approved these changes

2022-09-29 13:43 UTC, Nicojele requested changes

2022-09-29 13:43 UTC, Nicojele commented on homepage/Kontakt/style.css
> +.hyperlinkbar nav{
add space

2022-09-29 13:43 UTC, Nicojele commented on homepage/Startseite/styles.css
> +.hyperlinkbar nav{
add Space

2022-09-29 14:00 UTC, Nicojele approved these changes
Add BEM

2022-09-30 17:44 UTC, stefanluth commented on homepage/Portfolio/index.js
> +      document.getElementById("projekt_one_arrow").src = "img/Arrow_Right.png";
```suggestion
  const var = document.getElementById("projekt_one_arrow");
  if (menu1_is_open) {
    if (number == 1) {
      var.src = "img/Arrow_Right.png";
```

You can extract the elements into variables.

2022-10-05 06:36 UTC, DevBastiS requested changes

2022-10-05 06:36 UTC, DevBastiS commented on homepage/Kontakt/style.css
> +.hyperlinkbar {
```suggestion
.hyper-link-bar {
```

2022-10-05 06:36 UTC, DevBastiS commented on homepage/Kontakt/style.css
> +.content_container {
```suggestion
.content-container {
```

2022-10-17 08:15 UTC, stefanluth approved these changes

2022-10-24 06:14 UTC, merged