Add code from Week 1
Koch-Dustin/Cs50Kurs pull request #2
Opened 2022-08-05 08:16 UTC by Koch-Dustin

Changes:
1. Add Mario_less
2. Add Mario_more
3. Add Cash
4. Add Credit
5. Add Hello

2022-08-05 11:48 UTC, shoreal requested changes

2022-08-05 11:48 UTC, shoreal commented on Woche1/credit/credit.c
> +        printf("Invalid\n");
```suggestion
        } else if((firstTwoDigits == 34 || firstTwoDigits == 37) && count == 15) {
            printf("AmericanExpress\n");
        } else if((count == 13 || count == 16) && firstDigit == 4) {
            printf("Visa\n");
        } else {
            printf("Invalid\n");
        }

    } else {
        printf("Invalid\n");
```

2022-08-05 11:48 UTC, shoreal commented on Woche1/credit/credit.c
> +}
EOF missing (deutsch: End of File fehlt, also Leerzeile am Ende der Datei fehlt). Bitte noch hinzufügen.

2022-08-05 11:48 UTC, shoreal commented on Woche1/finished_cash/cash.c
> +    // Ask how many cents the customer is owed
```suggestion
```
Remove comments, we don't use them ever :D 

We are trying the approach of writing code, which is easily understandable without comments. The motto is: if you need comments to explain your code, your code isn't clean enough.

We only use comments in rare cases.

2022-08-05 11:48 UTC, shoreal commented on Woche1/finished_cash/cash.c
> +    printf("%i\n", coins);
```suggestion
    int quarters = calculate_quarters(cents);
    cents = cents - quarters * 25;

    int dimes = calculate_dimes(cents);
    cents = cents - dimes * 10;

    int nickels = calculate_nickels(cents);
    cents = cents - nickels * 5;

    int pennies = calculate_pennies(cents);
    cents = cents - pennies * 1;

    int coins = quarters + dimes + nickels + pennies;

    printf("%i\n", coins);
```

2022-08-05 11:48 UTC, shoreal commented on Woche1/finished_cash/cash.c
> +}
EOF missing

2022-08-05 11:48 UTC, shoreal commented on Woche1/finished_credit/credit.c
> +}
EOF missing

2022-08-05 11:48 UTC, shoreal commented on Woche1/finished_hello/hello.c
> +}
EOF missing

2022-08-05 11:48 UTC, shoreal commented on Woche1/finished_mario_less/mario-less.c
> +}
EOF missing

2022-08-05 11:48 UTC, shoreal commented on Woche1/finished_mario_more/mario-more.c
> +}
EOF missing

2022-08-05 11:48 UTC, shoreal commented on Woche1/finished_mario_more/mario-more.c
> +
```suggestion
    }
```

2022-08-05 11:49 UTC, shoreal requested changes

2022-08-05 11:49 UTC, shoreal commented on Woche1/finished_mario_less/mario-less.c
> +
```suggestion
```

2022-08-05 11:50 UTC, shoreal commented
I would suggest to configure your IDE (VSCode) to automatically add eof's (blank lines at the end of the file).

2022-08-05 13:00 UTC, stefanluth requested changes

2022-08-05 13:00 UTC, stefanluth commented on Woche1/finished_mario_less/mario-less.c
> +    do {
```suggestion
    int n;
    
    do {
```

2022-08-05 13:00 UTC, stefanluth commented on Woche1/finished_mario_less/mario-less.c
> +
```suggestion
    }
```

2022-08-05 13:00 UTC, stefanluth commented on Woche1/finished_mario_more/mario-more.c
> +    do {
```suggestion
    int n;
    
    do {
```

2022-08-05 13:00 UTC, stefanluth commented on Woche1/finished_mario_more/mario-more.c
> +
```suggestion
```

2022-08-08 06:21 UTC, DevBastiS requested changes

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +
```suggestion
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +    long long workingCC = ccard;
Isn't one long enough?

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +    long long workingCC = ccard;
Also what does "workingCC" mean?

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +    for(int i = 0; i < count - 2; i++) {
```suggestion
    for (int i = 0; i < count - 2; i++) {
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +    if(sum % 10 == 0) {
```suggestion
    if (sum % 10 == 0) {
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +        if(count == 16 && (firstTwoDigits == 51 || firstTwoDigits == 52 || firstTwoDigits == 53 || firstTwoDigits == 54 || firstTwoDigits == 55)) {
This if conditions are very hard to read. Try it this way:

```
bool CardIsMasterCard = <condition>;
if (CardIsMasterCard) {
  ....
}
```
This way the reader can read over the if clause like it is an english sentence.

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +        if(count == 16 && (firstTwoDigits == 51 || firstTwoDigits == 52 || firstTwoDigits == 53 || firstTwoDigits == 54 || firstTwoDigits == 55)) {
```suggestion
        if (count == 16 && (firstTwoDigits == 51 || firstTwoDigits == 52 || firstTwoDigits == 53 || firstTwoDigits == 54 || firstTwoDigits == 55)) {
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +        } else if((firstTwoDigits == 34 || firstTwoDigits == 37) && count == 15) {
```suggestion
        } else if ((firstTwoDigits == 34 || firstTwoDigits == 37) && count == 15) {
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +        } else if((count == 13 || count == 16) && firstDigit == 4) {
```suggestion
        } else if ((count == 13 || count == 16) && firstDigit == 4) {
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +    } else {
That if statement seem kinda long^^ Maybe you can use "early exit" here?

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/credit/credit.c
> +
```suggestion
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/finished_cash/cash.c
> +    return cents / pennies;
you could just return "cents" here.

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/finished_mario_less/mario-less.c
> +        }
```suggestion
        }
        
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/finished_mario_less/mario-less.c
> +
```suggestion
```

2022-08-08 06:21 UTC, DevBastiS commented on Woche1/finished_mario_more/mario-more.c
> +
```suggestion
```

2022-08-08 06:24 UTC, Koch-Dustin commented on Woche1/credit/credit.c
> +    long long workingCC = ccard;
"workingCC" is the input of the user that matches the condition.

2022-08-08 07:49 UTC, stefanluth approved these changes

2022-08-08 08:45 UTC, shoreal approved these changes

2022-08-08 10:51 UTC, merged