Woche2
Koch-Dustin/Cs50Kurs pull request #4
Opened 2022-08-11 06:45 UTC by Koch-Dustin

Changes:
1. Add caesar
2. Add readability
3. Add scrabble
4. Add substitution

2022-08-11 06:54 UTC, MKrips requested changes

2022-08-11 06:54 UTC, MKrips commented on Woche2/substitution/substitution.c
> +        }
```suggestion
        if(!CurrentLetterIsAlphabetic) {
            printf("Key must only contain alphabetic characters.\n");
            return 1;
        }
```
This would simplify this check as you want this to end the moment you find a non-alphalbetic character.

2022-08-11 06:54 UTC, MKrips commented on Woche2/substitution/substitution.c
> +        }
```suggestion
            if(tolower(argv[1][j]) == tolower(argv[1][k])) {
                printf("Key must not contain repeated characters.\n");
                return 1;
            }
            
        }
```
This can also be simplified.

2022-08-11 06:54 UTC, MKrips commented on Woche2/substitution/substitution.c
> +        bool CharacterIsUppercase = isalpha(plain[w]) && isupper(plain[w]);
```suggestion
        bool CharacterIsUppercase =  isupper(plain[w]);
```
You already checked before if you have only alphabetic characters, making this check redundant.

2022-08-11 13:43 UTC, stefanluth requested changes
Nur Code style reviewed, ob's funktioniert hab ich nicht getestet :D

2022-08-11 13:43 UTC, stefanluth commented on Woche2/caesar/caesar.c
> +        }
Spacing beachten: Leerzeichen nach keywords/vor oeffnende Klammern

```suggestion
        for (int j = 0; j < strlen(text); j++) {
            if (isupper(text[j])) {
                printf("%c", (text[j] - 65 + k) % 26 + 65);
            } else if (islower(text[j])) {
                printf("%c", (text[j] - 97 + k) % 26 + 97);
            } else {
                printf("%c", text[j]);
            }
        }
```

2022-08-11 13:43 UTC, stefanluth commented on Woche2/caesar/caesar.c
> +        }
In den anderen Dateien auch

2022-08-11 13:43 UTC, stefanluth commented on Woche2/scrabble/scrabble.c
> +    bool Score1IsHigher = score1 > score2;
```suggestion
    bool score1_is_higher = score1 > score2;

```

Variablen in [snake_case](https://en.wikipedia.org/wiki/Snake_case) halten

2022-08-11 13:43 UTC, stefanluth commented on Woche2/scrabble/scrabble.c
> +    bool Score1IsHigher = score1 > score2;
In den anderen Dateien auch

2022-08-11 13:43 UTC, stefanluth commented on Woche2/substitution/substitution.c
> +    string plain = get_string("Plainetext: ");
```suggestion
    string plain = get_string("Plaintext: ");
```

2022-08-11 13:43 UTC, stefanluth commented on Woche2/substitution/substitution.c
> +    return 0;
```suggestion

    return 0;
```

2022-08-11 13:59 UTC, stefanluth commented on Woche2/caesar/caesar.c
> +        printf("Ciphertext: ");
You iterate over the length of the input argument and each iteration you ask for a new plaintext input. Is that intended behavior?

2022-08-11 14:04 UTC, stefanluth commented on Woche2/readability/readability.c
> +    float S = (float) sentences / (float) words * 100;
Single letter variable names are a sin. 🥲

2022-08-11 14:09 UTC, stefanluth commented on Woche2/substitution/substitution.c
> +    }
```suggestion
        }

        count_key_characters++;
    }
```

2022-08-12 06:29 UTC, Koch-Dustin commented on Woche2/readability/readability.c
> +    float S = (float) sentences / (float) words * 100;
So war die vorgegebene Formel🥲

2022-08-12 06:35 UTC, DevBastiS requested changes

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/caesar/caesar.c
> +        if (!isdigit(argv[1][i])) {
When accessing two dimensional arrays or other "hard to read"-variables it is better to add another line of code to read from it and give that variable a good name like this:

```suggestion
        int someGoodName = argv[1][i];
        if (!isdigit(someGoodName)) {
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/caesar/caesar.c
> +            printf("Usage: ./caesar key\n");
```suggestion
            printf("Usage: ./caesar key\n");
            
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/readability/readability.c
> +
```suggestion
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/readability/readability.c
> +    }
```suggestion
    }
    
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/readability/readability.c
> +    if(index < 1) {
```suggestion
    if (index < 1) {
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/readability/readability.c
> +    }else if(index > 16) {
```suggestion
    } else if (index > 16) {
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/readability/readability.c
> +    }else {
```suggestion
    } else {
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/scrabble/scrabble.c
> +    if(Score1IsHigher) {
```suggestion
    if (Score1IsHigher) {

```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/scrabble/scrabble.c
> +    if(Score2IsHigher) {
```suggestion
    if (Score2IsHigher) {
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/scrabble/scrabble.c
> +        printf("Player 2 wins!\n");
```suggestion
        printf("Player 2 wins!\n");

```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/substitution/substitution.c
> +
```suggestion
```

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/substitution/substitution.c
> +            if(tolower(argv[1][j]) == tolower(argv[1][k])) {
Same with accessing variables

2022-08-12 06:35 UTC, DevBastiS commented on Woche2/substitution/substitution.c
> +    }
```suggestion
    for (int w = 0, x = strlen(plain); w < x; w++) {
        bool CharacterIsUppercase = isupper(plain[w]);
        bool CharacterisLowercase = islower(plain[w]);
        
        if (CharacterIsUppercase) {
            int upper = (plain[w] - 65);
            printf("%c", toupper(argv[1][upper]));
        } else if(CharacterisLowercase) {
            int lower = (plain[w] - 97);
            printf("%c", tolower(argv[1][lower]));
        } else {
            printf("%c", plain[w]);
        }
    }
```

2022-08-12 06:47 UTC, Koch-Dustin commented on Woche2/substitution/substitution.c
> +
Stefan hat gesagt "so"

2022-08-12 06:52 UTC, DevBastiS commented on Woche2/substitution/substitution.c
> +
Not sure what you mean please add a link to the comment of stefan

2022-08-12 07:26 UTC, DevBastiS commented on Woche2/substitution/substitution.c
> +
???

2022-08-12 07:31 UTC, stefanluth requested changes

2022-08-12 07:31 UTC, stefanluth commented on Woche2/caesar/caesar.c
> +    }
You iterate over the length of the input argument, and assign the same value to k each iteration. Is this intended behaviour?

2022-08-12 07:31 UTC, stefanluth commented on Woche2/readability/readability.c
> +    string UserText = get_string("Text: ");
Snake case :)

2022-08-12 07:31 UTC, stefanluth commented on Woche2/scrabble/scrabble.c
> +    }
You can re-use the first boolean and do an `else if` check instead of assigning two separate booleans and checking each separately.

2022-08-12 07:31 UTC, stefanluth commented on Woche2/scrabble/scrabble.c
> +}
Missing return.

2022-08-12 07:36 UTC, stefanluth commented on Woche2/scrabble/scrabble.c
> +            int current_letter_in_uppercase = toupper(word[i]) - number_to_transform_letter_into_uppercase;
```suggestion
            char current_letter_in_uppercase = toupper(word[i]);
            int numerical_value_of_letter = current_letter_in_uppercase - 'A';

```

This is what I meant. (Given it's correct)

2022-08-12 07:50 UTC, Koch-Dustin commented on Woche2/readability/readability.c
> +    string UserText = get_string("Text: ");
i don't know what you mean

2022-08-12 08:31 UTC, stefanluth commented on Woche2/readability/readability.c
> +    string UserText = get_string("Text: ");
Then don't just resolve the comment 😅 https://en.wikipedia.org/wiki/Snake_case

2022-08-12 08:34 UTC, stefanluth commented on Woche2/scrabble/scrabble.c
> +    }
Indentation. Also, I think I made a mistake. You will never reach the "Tie". So the way you had it before was correct. I apologise!

2022-08-15 06:27 UTC, DevBastiS approved these changes

2022-08-15 11:03 UTC, stefanluth approved these changes

2022-08-15 11:17 UTC, shoreal requested changes

2022-08-15 11:17 UTC, shoreal commented on Woche2/readability/readability.c
> +
```suggestion
```

2022-08-15 11:17 UTC, shoreal commented on Woche2/scrabble/scrabble.c
> +    } else if(score1 != score2) {
```suggestion
    } else if (score1 != score2) {

```

2022-08-15 11:17 UTC, shoreal commented on Woche2/scrabble/scrabble.c
> +    if (score1_is_higher) {
```suggestion
    if (score1 > score2) {

```

2022-08-15 11:17 UTC, shoreal commented on Woche2/scrabble/scrabble.c
> +    } else if(score1 != score2) {
```suggestion
    } else if(score1 < score2) {

```

2022-08-15 11:18 UTC, shoreal commented on Woche2/scrabble/scrabble.c
> +    if (score1_is_higher) {
speaking variables are good, but here is no need for this (imo). It's clear enough without it.

2022-08-15 11:23 UTC, shoreal requested changes

2022-08-15 11:23 UTC, shoreal commented on Woche2/scrabble/scrabble.c
> +        if (isalpha(word[i])) {
Here I would like to have a speaking variable, because I can't understand what `isalplha(word[i])` is meaning.

2022-08-15 11:23 UTC, shoreal commented on Woche2/substitution/substitution.c
> +    if (strlen(argv[1]) != 26) {
renaming the function-parameter or adding speaking variables would make it a lot easier to understand, what it does.

2022-08-15 14:06 UTC, merged