Woche3
Koch-Dustin/Cs50Kurs pull request #5
Opened 2022-08-19 12:51 UTC by Koch-Dustin

Changes:
1. plurality
2. runoff
3. tideman

2022-08-22 08:05 UTC, FrederikFricke commented on Woche3/runoff/runoff.c
> +    return 0;
```suggestion
    }
    
    return 0;
```

2022-08-22 08:05 UTC, FrederikFricke commented on Woche3/runoff/runoff.c
> +}
End of File

2022-08-22 08:05 UTC, FrederikFricke commented on Woche3/runoff/runoff.c
> +        int half_vote = voter_count / 2;
```suggestion
    int half_vote = voter_count / 2;
    for (int i = 0; i < voter_count; i++) {
```

2022-08-22 08:05 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +    return false;
```suggestion
    }
    
    return false;
```

2022-08-22 08:05 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +    return;
```suggestion
    }
    
    return;
```

2022-08-22 08:05 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +    return false;
```suggestion
    }
    
    return false;
```

2022-08-22 08:05 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +            else if (preferences[i][j] < preferences[j][i]) {
```suggestion
            } else if (preferences[i][j] < preferences[j][i]) {
```

2022-08-22 08:05 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +}
End of file

2022-08-22 08:26 UTC, FrederikFricke requested changes

2022-08-22 08:26 UTC, FrederikFricke commented on Woche3/runoff/runoff.c
> +{
```suggestion
void eliminate(int voted_person_with_the_least_votes) {
```

2022-08-22 08:26 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +
```suggestion
```

delete line

2022-08-22 08:26 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +
```suggestion
```

delete line

2022-08-22 08:26 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +
```suggestion
```

delete line

2022-08-22 08:26 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +
```suggestion 
```

delete line

2022-08-22 08:26 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +
```suggestion
```

delete line

2022-08-22 08:33 UTC, FrederikFricke requested changes

2022-08-22 08:33 UTC, FrederikFricke commented on Woche3/runoff/runoff.c
> +    for (int i = 0; i < candidate_count; i++) {
```suggestion
    }
    
    for (int i = 0; i < candidate_count; i++) {
```

2022-08-22 08:33 UTC, FrederikFricke commented on Woche3/tideman/tideman.c
> +        lock = true;
```suggestion
        }
        
        lock = true;
```

2022-08-22 08:37 UTC, FrederikFricke approved these changes

2022-08-22 11:18 UTC, stefanluth requested changes

2022-08-22 11:18 UTC, stefanluth commented on Woche3/sort/answers.txt
> +How do you know?: TODO
Remove the file if it's not needed.

2022-08-22 11:18 UTC, stefanluth commented on Woche3/plurality/plurality.c
> +        if (strcmp(candidates[i].name, name) == 0) {
```suggestion
        bool variable = strcmp(candidates[i].name, name) == 0;
        if (variable) {
```

Use variables for more complex if-conditions or when it's not obvious what the condition does. 

Also do this in the other files.

2022-08-22 11:18 UTC, stefanluth commented on Woche3/runoff/runoff.c
> +void eliminate(int min);
Sort by type and then alphabetically.

2022-08-22 11:18 UTC, stefanluth commented on Woche3/runoff/runoff.c
> +void eliminate(int min);
In other files as well.

2022-08-22 11:18 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +    return 0;
```suggestion
    print_winner();

    return 0;
```

2022-08-22 11:18 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +    }
```suggestion
    }
    
    return;
```

2022-08-22 11:18 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +    for(int i = 0; i < pair_count; i++) {
```suggestion
    for (int i = 0; i < pair_count; i++) {
```

2022-08-22 11:18 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +        for(int j = i + 1; j < pair_count; j++) {
```suggestion
        for (int j = i + 1; j < pair_count; j++) {
```

2022-08-22 11:18 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +            if(preference_votes_are_lower_than_maximum_votes) {
```suggestion
            if (preference_votes_are_lower_than_maximum_votes) {
```

In other files as well.

2022-08-22 11:19 UTC, stefanluth commented on Woche3/sort/answers.txt
> +How do you know?: TODO
The other files in `./sort` as well

2022-08-22 16:09 UTC, stefanluth requested changes
Delete `Woche3/.DS_Store`

2022-08-22 16:09 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +}
```suggestion
    }
    
    return;
}
```

2022-08-22 16:09 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +}
In other functions & files as well.

2022-08-22 16:13 UTC, stefanluth requested changes
Same remarks as my first review.

2022-08-22 16:13 UTC, stefanluth commented on Woche3/plurality/plurality.c
> +        if(candidates[i].votes == candidates[i + 1].votes) {
```suggestion
        if (candidates[i].votes == candidates[i + 1].votes) {
```

2022-08-22 16:13 UTC, stefanluth commented on Woche3/plurality/plurality.c
> +        if(candidates[i].votes == candidates[i + 1].votes) {
In other places as well.

2022-08-22 16:13 UTC, stefanluth commented on Woche3/runoff/runoff.c
> +        if (strcmp(name, candidates[i].name) == 0) {
Extract complex or unclear if-conditions to a variable.

2022-08-22 16:13 UTC, stefanluth commented on Woche3/runoff/runoff.c
> +        if (strcmp(name, candidates[i].name) == 0) {
In other places as well.

2022-08-25 06:23 UTC, DevBastiS approved these changes

2022-08-25 08:39 UTC, stefanluth requested changes
Still unresolved.

2022-08-25 14:04 UTC, stefanluth requested changes
Delete `Woche3/.DS_Store`

2022-08-25 14:05 UTC, stefanluth commented on Woche3/plurality/plurality.c
> +        if(candidates[i].votes == candidates[i + 1].votes) {
> In other places as well.

Still unresolved.

2022-08-29 06:23 UTC, stefanluth commented
https://github.com/Koch-Dustin/Cs50Kurs/pull/5#discussion_r955013350
https://github.com/Koch-Dustin/Cs50Kurs/pull/5#discussion_r955013543

Bitte erst resolven

2022-08-29 06:41 UTC, stefanluth commented on Woche3/runoff/runoff.c
> +        if(candidates[i].eliminated == false && candidates[i].votes != voted_person_with_the_least_votes) {
```suggestion
        if (candidates[i].eliminated == false && candidates[i].votes != voted_person_with_the_least_votes) {
```

2022-08-29 06:41 UTC, stefanluth commented on Woche3/runoff/runoff.c
> +        if(candidates[i].votes == voted_person_with_the_least_votes) {
```suggestion
        if (candidates[i].votes == voted_person_with_the_least_votes) {
```

2022-08-29 06:41 UTC, stefanluth commented on Woche3/runoff/runoff.c
> +        if(candidates[i].eliminated == false && candidates[i].votes != voted_person_with_the_least_votes) {
Extract if-condition to variable.

2022-08-29 06:41 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +        if (strcmp(name,  candidates[i]) == 0) {
Extract if-condition to variable.

2022-08-29 06:41 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +            if (preferences[i][j] > preferences[j][i]) {
Extract if-condition to variable.

2022-08-29 06:41 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +            } else if (preferences[i][j] < preferences[j][i]) {
Extract if-condition to variable.

2022-08-29 07:58 UTC, stefanluth commented on Woche3/tideman/tideman.c
> +        for(int j = i + 1; j < candidate_count; j++) {
```suggestion
    for (int i = 0; i < candidate_count; i++) {
        for (int j = i + 1; j < candidate_count; j++) {
```

2022-08-29 11:10 UTC, stefanluth approved these changes

2022-08-29 11:18 UTC, shoreal approved these changes

2022-08-29 13:32 UTC, merged