Woche4
Koch-Dustin/Cs50Kurs pull request #6
Opened 2022-09-01 14:10 UTC by Koch-Dustin

Changes:
   1.Add Filter-less
   2.Add Filter-more
   3.Add Volume

2022-09-02 07:10 UTC, FrederikFricke requested changes

2022-09-02 07:10 UTC, FrederikFricke commented on Woche4/filter-more/helpers.c
> +                }
```suggestion
                   RGBTRIPLE imageTripple = image[i + h][j + w];
                    GxR += imageTriple.rgbtRed * Gx[h + 1][w + 1];
                    GxG += imageTriple.rgbtGreen * Gx[h + 1][w + 1];
                    GxB += imageTriple.rgbtBlue * Gx[h + 1][w + 1];

                    GyR += imageTriple.rgbtRed * Gy[h + 1][w + 1];
                    GyG += imageTriple.rgbtGreen * Gy[h + 1][w + 1];
                    GyB += imageTriple.rgbtBlue * Gy[h + 1][w + 1];
                }
```

by using a variable in this case `imageTriple` you 'iterate' through the array once and not many times.

2022-09-02 07:10 UTC, FrederikFricke commented on Woche4/volume/volume.c
> +        return 1;
```suggestion
int main(int argc, char *argv[])
{

    if (argc != 4)
    {
        printf("Usage: ./volume input.wav output.wav factor\n");
        return 1;
```

same here. be consistent with the curly brackets

2022-09-02 07:23 UTC, stefanluth requested changes

2022-09-02 07:23 UTC, stefanluth commented on Woche4/filter-more/helpers.c
> +        for(int j = 0; j < width; j++) {
```suggestion
    for (int i = 0; i < height; i ++) {
        for (int j = 0; j < width; j++) {
```
Everywhere :P

2022-09-02 07:23 UTC, stefanluth commented on Woche4/filter-more/helpers.c
> +    int sepiaBlue;
```suggestion
void sepia(int height, int width, RGBTRIPLE image[height][width]) {
    int sepiaBlue;
```

2022-09-02 07:23 UTC, stefanluth commented on Woche4/filter-more/helpers.c
> +    for (int i = 0; i < height; i++) {
```suggestion
    int sepiaGreen;

    for (int i = 0; i < height; i++) {
```

2022-09-02 07:23 UTC, stefanluth commented on Woche4/filter-more/helpers.c
> +            if(k < 0 || l < 0 || k >= height || l >= width) {
```suggestion
            if (k < 0 || l < 0 || k >= height || l >= width) {
```
Everwhere :P

2022-09-02 07:23 UTC, stefanluth commented on Woche4/filter-less/helpers.c
> +}
```suggestion
    }
    return;
}
```

2022-09-02 08:45 UTC, DevBastiS requested changes
Remove the submodule from filter more.

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-less/filter.c
> +    // Remember filenames
Remove comments.

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-more/filter.c
> +    // Define allowable filters
Remove comments.

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-more/filter.c
> +        printf("Unsupported file format.\n");
```suggestion
        printf("Unsupported file format.\n");
        
```

Always add a whiteline before return statements except they are the only statement in a block.

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-more/helpers.c
> +    if(RGB > 255) {
```suggestion
    if (RGB > 255)
    {
```

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-more/helpers.c
> +    if(RGB > 255) {
```suggestion
    if (RGB > 255) {
```

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-more/helpers.c
> +    }
```suggestion
    }
    
```

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-more/helpers.c
> +    for (int i = 0; i < height; i++) {
```suggestion
    for (int i = 0; i < height; i++)
    {
```

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-more/helpers.c
> +        for (int j = 0; j < width; j++) {
```suggestion
        for (int j = 0; j < width; j++)
        {
```

2022-09-02 08:45 UTC, DevBastiS commented on Woche4/filter-more/helpers.c
> +        for(int j = 0; j < width / 2; j++) {
Move braces, be consistend in your own code.

2022-09-02 11:41 UTC, stefanluth requested changes
`for(` -> `for (`
`if(` -> `if (`

2022-09-02 12:00 UTC, MKrips requested changes
There were some conversations you marked as resolved when on my side they were not. They were maybe resolved during one of the commits you did while I did this review, but please look again if you actually resolved all conversations.

2022-09-02 12:56 UTC, FrederikFricke requested changes

2022-09-02 12:56 UTC, FrederikFricke commented on Woche4/filter-less/filter.c
> +    }
```suggestion
        printf("Unsupported file format.\n");
        
        return 6;
    }
```

2022-09-02 12:56 UTC, FrederikFricke commented on Woche4/filter-less/filter.c
> +    }
```suggestion
        fclose(inptr);
        
        return 7;
    }
```

2022-09-02 12:56 UTC, FrederikFricke commented on Woche4/filter-more/helpers.c
> +                    GyB += imageTripple.rgbtBlue * Gy[h + 1][w + 1];
you could replace `Gx[h + 1][w + 1]` and `Gy[h + 1][w + 1]` with varibales like that: 

```suggestion
                   int GxValue = Gx[h + 1][w + 1];
                   int GyValue = Gy[h + 1][w + 1];

                    GxR += imageTripple.rgbtRed * GxValue;
                    GxG += imageTripple.rgbtGreen * GxValue;
                    GxB += imageTripple.rgbtBlue * GxValue;

                    GyR += imageTripple.rgbtRed * GyValue;
                    GyG += imageTripple.rgbtGreen * GyValue;
                    GyB += imageTripple.rgbtBlue * GyValue;
```

2022-09-02 12:56 UTC, FrederikFricke commented on Woche4/filter-less/helpers.c
> +
```suggestion
            RGBTRIPLE imgTriple = image[i][j];

            sepiaBlue = limit(round(0.272 * imgTriple.rgbtRed + 0.534 * imgTriple.rgbtGreen + 0.131 * imgTriple.rgbtBlue));
            sepiaGreen = limit(round(0.349 * imgTriple.rgbtRed + 0.686 * imgTriple.rgbtGreen + 0.168 * imgTriple.rgbtBlue));
            sepiaRed = limit(round(0.393 * imgTriple.rgbtRed + 0.769 * imgTriple.rgbtGreen + 0.189 * imgTriple.rgbtBlue));

```

2022-09-02 20:28 UTC, FrederikFricke requested changes

2022-09-02 20:28 UTC, FrederikFricke commented on Woche4/filter-less/filter.c
> +    }
```suggestion
        printf("Invalid filter.\n");
        
        return 1;
    }
```

2022-09-02 20:28 UTC, FrederikFricke commented on Woche4/filter-more/helpers.c
> +            counter++;
```suggestion
            if (k < 0 || l < 0 || k >= height || l >= width) continue;
            
            RGBTRIPLE imageTriple = image[k][i];
            if (color_position == 0) {
                sum += imageTriple.rgbtRed;
            } else if (color_position == 1) {
                sum += imageTriple.rgbtGreen;
            } else {
                sum += imageTriple.rgbtBlue;
            }
            counter++;
```

2022-09-02 20:28 UTC, FrederikFricke commented on Woche4/filter-more/helpers.c
> +
```suggestion
                    if (i + h < 0 || i + h > height - 1) continue;
                        
                    if (j + w < 0 || j + w > width - 1) continue;

```

2022-09-02 20:40 UTC, FrederikFricke approved these changes

2022-09-05 11:32 UTC, stefanluth commented
> `for(` -> `for (` `if(` -> `if (`

this still

2022-09-06 09:03 UTC, Koch-Dustin commented
> > `for(` -> `for (` `if(` -> `if (`
> 
> this still



> > `for(` -> `for (` `if(` -> `if (`
> 
> this still

Should be changed now

2022-09-06 13:23 UTC, stefanluth commented on Woche4/filter-less/helpers.c
> +            if(k < 0 || l < 0 || k >= height || l >= width) {
```suggestion
            if (k < 0 || l < 0 || k >= height || l >= width) {
```
this still

2022-09-06 14:07 UTC, DevBastiS approved these changes

2022-09-06 14:07 UTC, DevBastiS commented on Woche4/filter-less/helpers.c
> +
```suggestion
```

2022-09-08 06:39 UTC, NiclasPodzierski requested changes

2022-09-08 06:39 UTC, NiclasPodzierski commented on Woche4/filter-more/helpers.c
> +            }
This is similar to what you have done in your sepia-filter in line 36 to 38. Therefore you should make use of your limit function in this case, too, instead of re-implementing the same logic.
```suggestion
            temp[i][j].rgbtRed = filter(round(sqrt((GxR * GxR  + GyR * GyR))));
            temp[i][j].rgbtGreen = filter(round(sqrt((GxG * GxG + GyG * GyG))));
            temp[i][j].rgbtBlue = filter(round(sqrt((GxB * GxB + GyB * GyB))));
```

2022-09-13 09:36 UTC, merged