🚧 Woche5
Koch-Dustin/Cs50Kurs pull request #7
Opened 2022-09-02 12:32 UTC by Koch-Dustin

Changes:
   1. Add Inheritance
   2. Add Speller

PR: #

2022-09-05 07:04 UTC, FrederikFricke requested changes

2022-09-05 07:04 UTC, FrederikFricke commented on Woche5/speller/speller.c
> +    if (file == NULL) {
```suggestion
    char *text = (argc == 3) ? argv[2] : argv[1];
    FILE *file = fopen(text, "r");
    
    if (file == NULL) {
```

2022-09-05 11:37 UTC, FrederikFricke requested changes

2022-09-05 11:37 UTC, FrederikFricke commented on Woche5/inheritance/inheritance.c
> +    char alleles[2];
```suggestion
typedef struct person {
    struct person *parents[2];
    char alleles[2];
```

2022-09-05 11:37 UTC, FrederikFricke commented on Woche5/speller/dictionary.c
> +    fclose(file);
```suggestion

        table[index] = n;
        total_words++;
    }

    fclose(file);
```

2022-09-05 11:37 UTC, FrederikFricke commented on Woche5/speller/dictionary.c
> +}
```suggestion
    }
    
    return true;
}
```

2022-09-06 09:05 UTC, FrederikFricke approved these changes

2022-09-06 13:27 UTC, stefanluth requested changes

2022-09-06 13:27 UTC, stefanluth commented on Woche5/speller/dictionary.c
> +}
```suggestion
unsigned int size(void) {
    return total_words;
}
```

2022-09-06 13:32 UTC, stefanluth requested changes

2022-09-06 13:32 UTC, stefanluth commented on Woche5/speller/speller.c
> +
```suggestion
    while (fread(&c, sizeof(char), 1, file)) {
        if (isalpha(c) || (c == '\'' && index > 0)) {
            word[index] = c;
            index++;

            if (index > LENGTH) {
```

2022-09-06 13:32 UTC, stefanluth commented on Woche5/speller/speller.c
> +            words++;
```suggestion
            word[index] = '\0';
            words++;
```

2022-09-06 13:32 UTC, stefanluth commented on Woche5/speller/speller.c
> +int main(int argc, char *argv[]) {
The main is huge, split it into more functions.

2022-09-06 14:08 UTC, DevBastiS requested changes

2022-09-06 14:08 UTC, DevBastiS commented on Woche5/inheritance/inheritance.c
> +    }
Is it possible to solve this with a switch case?

2022-09-08 12:39 UTC, Koch-Dustin commented
> ![Screenshot 2022-09-08 at 14 13 34](https://user-images.githubusercontent.com/80166473/189120500-e2d2a8ca-c61c-4d2c-af34-3380990bdd90.png)

Should be done

2022-09-08 12:43 UTC, stefanluth requested changes

2022-09-08 12:43 UTC, stefanluth commented on Woche5/inheritance/inheritance.c
> +}
Missing returns. Other occurrences as well.

2022-09-13 12:57 UTC, stefanluth requested changes
Please check missing returns and returning the correct types. There are more than I commented.

2022-09-13 12:57 UTC, stefanluth commented on Woche5/inheritance/inheritance.c
> +}
This function is supposed to return a `char` but it returns `void`.

2022-09-13 12:57 UTC, stefanluth commented on Woche5/inheritance/inheritance.c
> +}
This function is supposed to return an `int` but it returns `void`.

2022-09-13 12:57 UTC, stefanluth commented on Woche5/speller/dictionary.c
> +}
This function always returns `true`.

2022-09-13 12:57 UTC, stefanluth commented on Woche5/speller/speller.c
> +}
This function is supposed to return `void` but returns `int`. Also a missing return statement at the end.

2022-09-16 06:18 UTC, DevBastiS approved these changes
Wait for @stefanluth's approval.

2022-09-16 06:55 UTC, merged

2022-09-16 08:54 UTC, stefanluth commented
Or not :D