Woche6
Koch-Dustin/Cs50Kurs pull request #8
Opened 2022-09-15 06:29 UTC by Koch-Dustin

Changes:
   Add dna
   Add hello
   Add mario-less
   Add mario-more
   Add cash
   Add credit
   Add readability

PR #8

2022-09-15 07:13 UTC, FrederikFricke requested changes

2022-09-15 07:13 UTC, FrederikFricke commented on Woche6/dna/dna.py
> +        while True:
```suggestion
    for i in range(sequence_length):
        count = 0

        while True:
```

2022-09-15 07:13 UTC, FrederikFricke commented on Woche6/dna/dna.py
> +                break
```suggestion
            if sequence[start:end] == subsequence:
                count += 1
            else:
                break
```

2022-09-15 07:17 UTC, MKrips requested changes

2022-09-15 07:17 UTC, MKrips commented on Woche6/dna/dna.py
> +    for i in range(1, len(reader.fieldnames)):
```suggestion
    for i in range(1, len(file_reader.fieldnames)):
```
This should be the specific CsvReader that read the file, not any generic one.

2022-09-15 07:17 UTC, MKrips commented on Woche6/dna/dna.py
> +                    max_counts[i - 1] = str_count
This is what you are supposed to do the longest_match function for.

2022-09-15 07:17 UTC, MKrips commented on Woche6/dna/dna.py
> +def longest_match(sequence, subsequence):
This function is not called, making it currently unnecessary.

2022-09-15 07:17 UTC, MKrips commented on Woche6/mario-less/main.py
> +def input_number(message):
You never use this function

2022-09-15 07:17 UTC, MKrips commented on Woche6/mario-less/main.py
> +    print(" " * (height-1-i))
```suggestion
    print("#" * (i+1), end="  ")
```

2022-09-15 07:17 UTC, MKrips commented on Woche6/mario-more/mario-more.py
> +    print(" " * (height-1-i))
```suggestion
    print("#" * (i+1), end="")
```

2022-09-15 07:17 UTC, MKrips commented on Woche6/sentimental-credit/credit.py
> +workingCC = credit_card_number // 10
```suggestion
workingCC = credit_card_number // divisor
```
If you defined a variable, do not just use it sometimes, but everytime you can

2022-09-15 07:17 UTC, MKrips commented on Woche6/sentimental-credit/credit.py
> +def check_which_type_card_is():
Do not declare functions randomly in the middle, declare them before your code

2022-09-16 08:44 UTC, stefanluth requested changes

2022-09-16 08:44 UTC, stefanluth commented on Woche6/mario-more/mario-more.py
> +    print("#" * (i+1), end="")
```suggestion
    print(" " * (height - 1 - i), end="")
    print("#" * (i + 1), end="  ")
    print("#" * (i + 1), end="")
```

2022-09-16 08:44 UTC, stefanluth commented on Woche6/sentimental-credit/credit.py
> +        card_is_master_card = count == 16 and (first_two_digits == 51 or first_two_digits == 52 or first_two_digits == 53 or first_two_digits == 54 or first_two_digits == 55)
```suggestion
        card_is_master_card = count == 16 and (
            first_two_digits == 51
            or first_two_digits == 52
            or first_two_digits == 53
            or first_two_digits == 54
            or first_two_digits == 55
        )
```

2022-09-16 08:44 UTC, stefanluth commented on Woche6/sentimental-readability/readability.py
> +    print(f'Grade {index}')
```suggestion
    print(f"Grade {index}")
```

2022-09-19 05:40 UTC, DevBastiS approved these changes

2022-09-20 07:35 UTC, stefanluth approved these changes

2022-09-22 05:56 UTC, merged