Woche7
Koch-Dustin/Cs50Kurs pull request #9
Opened 2022-09-15 06:31 UTC by Koch-Dustin

Changes:
   Add fiftyville
   Add movies
   Add songs

PR: #9

2022-09-15 07:06 UTC, FrederikFricke requested changes

2022-09-15 07:06 UTC, FrederikFricke commented on movies/11.sql
> +SELECT movies.title FROM people JOIN stars ON people.id = stars.person_id JOIN movies ON stars.movie_id = movies.id JOIN ratings ON movies.id = ratings.movie_id WHERE people.name = "Chadwick Boseman"
```suggestion
SELECT movies.title
    FROM people 
    JOIN stars 
       ON people.id = stars.person_id 
    JOIN movies 
       ON stars.movie_id = movies.id 
    JOIN ratings
       ON movies.id = ratings.movie_id
       WHERE people.name = "Chadwick Boseman"
       ORDER BY rating DESC LIMIT 5;
    
```

stick to the convention you used on the `fiftyville/log.sql` file. this is also for the other `.sql` files.

2022-09-16 06:21 UTC, DevBastiS requested changes

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> +
```suggestion
```

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> +SELECT description FROM crime_scene_reports WHERE year = 2021 AND month = 7 AND day = 28 AND street = 'Humphrey Street';
```suggestion
SELECT description FROM crime_scene_reports
WHERE year = 2021 AND month = 7
  AND day = 28
  AND street = 'Humphrey Street';
```

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> +
```suggestion
```

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> +   AND transaction_type = 'withdraw';
```suggestion
   AND transaction_type = 'withdraw';
   
```

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> +
```suggestion
```

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> +-- Raymond hört gespräch um ein Ticket für eine Flugbuchung für den frühsten Flug am July 29, 2021
Wenn schon Kommentare dann bitte richtiges deutsch, sonst die Kommentare entfernen bitte.

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> + ORDER BY flights.hour, flights.minute;
```suggestion
 ORDER BY flights.hour, flights.minute;
 
```

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> + ORDER BY passengers.passport_number;
```suggestion
 ORDER BY passengers.passport_number;
 
```

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> + ORDER BY phone_calls.duration;
```suggestion
 ORDER BY phone_calls.duration;
 
```

2022-09-16 06:21 UTC, DevBastiS commented on fiftyville/log.sql
> +
```suggestion
```

2022-09-16 06:21 UTC, DevBastiS commented on movies/1.sql
> +WHERE year = 2008;
Missing EOF in many files.

2022-09-16 06:21 UTC, DevBastiS commented on songs/3.sql
> +SELECT name FROM songs ORDER BY duration_ms DESC LIMIT 5;
Structure this queries like you did with the others.
```suggestion
SELECT name FROM songs
ORDER BY duration_ms DESC
LIMIT 5;
```

2022-09-16 08:55 UTC, stefanluth requested changes
Add EOFs

2022-09-19 05:42 UTC, DevBastiS requested changes

2022-09-19 05:42 UTC, DevBastiS commented on songs/1.sql
> +SELECT title FROM movies WHERE year = 2008;
Missing EOF in many files

2022-09-19 05:42 UTC, DevBastiS commented on songs/3.sql
> +SELECT name FROM songs ORDER BY duration_ms DESC LIMIT 5;
Still open.

2022-09-20 07:37 UTC, stefanluth requested changes
Choose one code style

<img width="160" alt="Screenshot 2022-09-20 at 09 37 20" src="https://user-images.githubusercontent.com/80166473/191196214-d01ea1aa-5e63-48a6-a437-b948cf676904.png">
<img width="219" alt="Screenshot 2022-09-20 at 09 37 17" src="https://user-images.githubusercontent.com/80166473/191196218-874d7696-a628-401b-b8b0-72abae4e7f87.png">

2022-09-21 05:57 UTC, DevBastiS approved these changes
What Stefan said.

2022-09-22 08:34 UTC, stefanluth requested changes
Indentation is still off :)

2022-09-26 07:28 UTC, stefanluth reviewed
:)

2022-09-26 07:28 UTC, stefanluth commented on fiftyville/log.sql
> + -- Zeugen: Eugene, Raymond und Ruth
```suggestion
-- Zeugen: Eugene, Raymond und Ruth
```

2022-09-26 07:28 UTC, stefanluth commented on fiftyville/log.sql
> + -- Flüge vom 29. July überprüfen und nach Zeit sortieren
```suggestion
-- Flüge vom 29. July überprüfen und nach Zeit sortieren
```

2022-09-29 12:01 UTC, stefanluth approved these changes

2022-09-29 13:14 UTC, merged